# Generated by Django 5.2.4 on 2025-07-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('loan_account_no', models.CharField(max_length=30, verbose_name='Loan Account No.')),
                ('ifsc_code', models.CharField(max_length=20, verbose_name='IFSC Code')),
                ('bank_branch', models.CharField(max_length=50, verbose_name='Bank Branch')),
                ('branch_address', models.TextField(verbose_name='Branch Address')),
            ],
        ),
        migrations.CreateModel(
            name='CreateApprovalLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('pancard', models.CharField(max_length=10)),
                ('aadharcard', models.CharField(max_length=12)),
                ('loanamount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Loan Amount (₹)')),
                ('interest', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Interest Rate (%)')),
                ('loan_duration_value', models.PositiveIntegerField(verbose_name='Loan Duration')),
                ('loan_duration_type', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=5, verbose_name='Duration Type')),
                ('insurance', models.CharField(max_length=50, verbose_name='Insurance Charge Refund')),
                ('customeraccount', models.CharField(max_length=20)),
                ('customername', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
                ('branchname', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
