# Generated by Django 5.2.4 on 2025-07-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetail',
            name='bank_branch',
        ),
        migrations.RemoveField(
            model_name='bankdetail',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='bankdetail',
            name='branch_address',
        ),
        migrations.RemoveField(
            model_name='bankdetail',
            name='loan_account_no',
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='account_name',
            field=models.CharField(default=1, max_length=100, verbose_name='account_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='account_number',
            field=models.CharField(default=1, max_length=30, verbose_name='account_number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='branch_name',
            field=models.CharField(default=1, max_length=50, verbose_name='branch_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='ifsc_code',
            field=models.CharField(max_length=20, verbose_name='ifsc_code'),
        ),
    ]
