# Generated by Django 5.2.4 on 2025-07-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_bankdetail_bank_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createapprovalletter',
            name='company_account_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createapprovalletter',
            name='company_bank_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createapprovalletter',
            name='company_branch',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createapprovalletter',
            name='company_ifsc',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createapprovalletter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
