# Generated by Django 5.2.4 on 2025-07-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_createapprovalletter_company_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createapprovalletter',
            name='company_account_number',
        ),
        migrations.RemoveField(
            model_name='createapprovalletter',
            name='company_bank_name',
        ),
        migrations.RemoveField(
            model_name='createapprovalletter',
            name='company_branch',
        ),
        migrations.RemoveField(
            model_name='createapprovalletter',
            name='company_ifsc',
        ),
    ]
