# Generated by Django 5.2.4 on 2025-07-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_createapprovalletter_company_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createapprovalletter',
            name='company_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='createapprovalletter',
            name='company_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='createapprovalletter',
            name='company_branch_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='createapprovalletter',
            name='company_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
