# Generated by Django 5.2.4 on 2025-07-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_createapprovalletter_company_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_type', models.CharField(choices=[('mudra', 'Mudra Finance'), ('kreditbee', 'Kredit Bee'), ('indiabulls', 'IndiaBulls Dhani Finance')], default='kreditbee', max_length=50)),
            ],
        ),
    ]
