# Generated by Django 5.2.4 on 2025-07-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_approvalletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalLetter',
        ),
        migrations.AddField(
            model_name='createapprovalletter',
            name='finance_type',
            field=models.CharField(choices=[('mudra', 'Mudra Finance'), ('kreditbee', 'Kredit Bee'), ('indiabulls', 'IndiaBulls Dhani Finance')], default='kreditbee', max_length=50, verbose_name='Finance Type'),
        ),
    ]
